# Defaults can be found here: https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'spec/fixtures/**/*'
    - 'lib/danger/plugin_support/plugin_parser.rb'

Metrics/LineLength:
  Exclude:
    - 'spec/*'
    - 'danger-jazzy.gemspec'

Style/IfUnlessModifier:
  Exclude:
    - 'Gemfile'

Style/SpecialGlobalVars:
  Exclude:
    - 'danger-jazzy.gemspec'

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
